name: auto build engine

on: 
  release:
    types: [published]
  schedule:
    - cron: "0 16 * * *"
  push:
    branches: 
      - master
  watch:
    types: [started]
   
jobs:
  build:
    name: Build Magisk
    runs-on: ubuntu-24.04
    steps:
      - name: Check out
        uses: actions/checkout@main
        with:
          repository: "topjohnwu/Magisk"
          #ref: "0d9ec0931b98c930bf24bb5c52723e6d0a5ebdf4"
          ref: ""
          submodules: "recursive"
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@main
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Set up Python 3
        uses: actions/setup-python@main
        with:
          python-version: "3.x"

      - name: Set up NDK
        run: python build.py -v ndk

      - name: Patch
        run: |
          wget --no-check-certificate https://raw.githubusercontent.com/ActiveIce/Magisk_zygote64_32/master/zygote64_32.patch -O zygote64_32.patch
          git apply zygote64_32.patch --reject
  
      - name: Config
        run: |
          echo ${{ secrets.KEYSTORE }} | base64 --decode > keystore.jks
          echo keyStore=keystore.jks >> config.prop
          echo keyStorePass=${{ secrets.KEYSTOREPASS }} >> config.prop
          echo keyAlias=${{ secrets.KEYALIAS }} >> config.prop
          echo keyPass=${{ secrets.KEYPASS }} >> config.prop

      - name: Build release
        run: |
          python build.py -vr all

      - name: Update canary
        run: |
          rev=$(git rev-parse --short=8 HEAD)
          link=https://raw.githubusercontent.com/ActiveIce/Magisk_zygote64_32/master/
          wget --no-check-certificate https://raw.githubusercontent.com/topjohnwu/magisk-files/master/canary.json -O out/canary.json
          sed -i "s#\"version\": \".*\"#\"version\": \"${rev}\"#" out/canary.json
          sed -i "s#\"link\": \".*app-release.apk\"#\"link\": \"${link}app-release.apk\"#g" out/canary.json
          sed -i "s#\"link\": \".*stub-release.apk\"#\"link\": \"${link}stub-release.apk\"#g" out/canary.json

      - name: Upload artifact
        uses: actions/upload-artifact@main
        with:
          name: magisk
          path: |
            out/app-release.apk
            out/stub-release.apk
            out/canary.json

  push:
    needs: build
    runs-on: ubuntu-24.04
    
    steps:
    - name: Checkout
      uses: actions/checkout@main
    
    - name: Clean
      run: |
        rm *.apk *.json
    
    - name: Download artifact
      uses: actions/download-artifact@main
      with:
        name: magisk
        path: ./
    
    - name: Commit
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git checkout --orphan new_branch
        git add -A
        git commit -am "update new file"
        git branch -D master
        git branch -m master
        git push origin master --force
